In [12]:
#Problem  1
#Convert a 1D array to a 2D array with 2 rows

import numpy as np
A=np.arange(10)
print(A)
B=A.reshape(2,-1)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
#Problem 2
#Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
odd=[]
for i in arr:
    if i % 2 != 0:
        odd.append(i)
print(odd)

[0 1 2 3 4 5 6 7 8 9]
[1, 3, 5, 7, 9]


In [10]:
# Problem 3
# Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [14]:
# Problem 4
# Replace all odd numbers in arr with -1 without changing arr

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.vstack((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# Problem 5
# Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.hstack((a,b))
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [34]:
# Problem 7
# Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3])
b=np.repeat(a,3)
r1 = np.tile(a,3)
c=np.concatenate((b,r1))
print(c)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [39]:
# Problem 8
# From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c=np.setdiff1d(a,b)

print(c)


[1 2 3 4]


In [41]:
# Problem 9
# Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(np.in1d(a, b))[0]
print(c)


[1 3 5 7]


In [51]:
# Problem 10
# Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
print(arr)
b=arr[:, [0, 1]] = arr[:, [1, 0]]
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0]
 [4 3]
 [7 6]]


In [140]:
# Problem 11
# From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
b=np.clip(a, a_min=10, a_max=30)
print(b)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [74]:
# Problem 12
# Compute the counts of unique values row-wise.

np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)
# b=np.unique(arr)
# print(b)
row,col = np.shape(arr) 
for i in range(row):
    a,c = np.unique(arr[i], return_counts = True)
    print(c)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[1 2 1 1 1 2 2]
[2 1 3 1 1 1 1]
[3 2 3 1 1]
[1 2 1 1 2 1 2]
[2 2 2 1 1 1 1]
[1 1 1 1 1 2 2 1]


In [80]:
# Problem 13
# Compute the one-hot encodings (dummy binary variables for each unique value in the array)


values = [1, 0, 3]
n_values = np.max(values) + 1
np.eye(n_values)[values]


array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [87]:
# Problem 14
# Create the ranks for the given numeric array a.

np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
b=a.argsort()
ranks_array = np.empty_like(b)
ranks_array[b] = np.arange(len(a))
print(ranks_array)

[ 9  4 15  0 17 16 17  8  9  0]

Rank of each item of the said array:
[4 2 6 0 8 7 9 3 5 1]


In [91]:
# Problem 15
# Create a rank array of the same shape as a given numeric array a.

np.random.seed(10)
a = np.random.randint(20, size=[2,5])

b=a.ravel().argsort().argsort().reshape(a.shape)
print(b)



[[4 2 6 0 8]
 [7 9 3 5 1]]


In [107]:
# Problem 16
# Compute the min-by-max for each row for given 2d numpy array

np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
b=np.min(a,axis=1)
c=np.max(a,axis=1)
print(b)
print(c)
d=np.divide(b,c)
print(d)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[4 1 3 3 1]
[9 8 6 3 9]
[0.44444444 0.125      0.5        1.         0.11111111]


In [115]:
# Problem 17
# Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False


uniques = np.unique(a)
result = []
for i in a:
    if i not in uniques:
        result.append(True)
    else:
        result.append(False)
        uniques = np.delete(uniques, np.where(uniques == i))
   

np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
print(duplicates(a))




Array:  [0 0 3 0 2 4 2 2 2 2]
[False, True, False, True, False, False, True, True, True, True]


In [117]:
# Problem 18
# Drop all nan values from a 1D numpy array
a=np.array([1,2,3,np.nan,5,6,7,np.nan])
x = a[~np.isnan(a)]
print(x)

[1. 2. 3. 5. 6. 7.]


In [120]:
# Problem 19
# Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
b=np.argmax(a)
print(b)

2


In [122]:
# Problem 20
# Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
c=a_2d -b_1d[:,None]
print(c)
        

[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [126]:
# Problem 21
# Find the index of 5th repetition of number 1 in x.

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
b=np.where(x==1)[0]
print(b[4])

8


In [129]:
# Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
a=np.arange(start=5, stop=33, step=3)
print(a)

[ 5  8 11 14 17 20 23 26 29 32]


In [132]:
# Problem 23
# From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]


arr = np.arange(15) 
arr
def gen_strides(a, stride_len=2, window_len=4):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
